nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    documentation:
        info:
            title: Budget API
            description: All API related Budget application
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value should be : {Bearer TOKEN} obtain by /api/login_check'
                name: Authorization
                in: header
                default: 'Bearer '
        paths:
            /api/login_check:
                post:
                    tags:
                        - Security
                    sumarry: Authentication
                parameters:
                    -   in: body
                        name: body
                        required: true
                        schema:
                            $ref: "#/definitions/AuthenticationContent"
            #### Account ####
            /api/accounts:
                post:
                    tags:
                        - Account
                    sumarry: Registration
                    description: Allow user to register to application
                parameters:
                    -   in: body
                        name: body
                        required: true
                        schema:
                            $ref: "#/definitions/RegistrationInput"
                responses:
                    '201':
                        description: Successful registration
                    '400':
                        description: Bad request. Check your request
            /api/accounts/confirm:
                post:
                    tags:
                        - Account
                    summarry: Confirmation account
                    description: Allow user to confirm registration
                parameters:
                    - in: body
                      name: body
                      required: true
                      schema:
                          $ref: "#/definitions/EmailInput"
                    - in: query
                      name: tokenActivation
                      type: string
                      required: true
                      description: Token activation
                responses:
                    '200':
                        description: Successful registration confirmation
                        schema:
                            $ref: "#/definitions/AuthenticationOutput"
                    '400':
                        description: Bad request. Check your request.
            /api/accounts/recovery-password:
                post:
                    tags:
                        - Account
                    summarry: Recovery password
                    description: Send a recovery password request.
                parameters:
                    - in: body
                      name: body
                      required: true
                      schema:
                          $ref: "#/definitions/EmailInput"
                responses:
                    '201':
                        description: Successful recovery password request
                    '400':
                        description: Bad request. Check your request
            /api/accounts/define-new-password:
                post:
                    tags:
                        - Account
                    summarry: Reinit password
                    description: Send a request to reinit password
                parameters:
                    - in: body
                      name: body
                      required: true
                      schema:
                          $ref: "#/definitions/DefineNewPasswordInput"
                    - in: query
                      name: tokenResetPassword
                      type: string
                      required: true
                      description: Token reset password to define new password
                responses:
                    '200':
                        description: Successful reset password
                        schema:
                            $ref: "#/definitions/AuthenticationOutput"
                    '400':
                        description: Bad request. Please check your request
            #### Bank ####
            /api/banks:
                get:
                    tags:
                        - Bank
                    summary: List bank available
                    description: Return list bank available according different parameters
                parameters:
                    - in: query
                      name: search
                      type: string
                      required: true
                      description: Search terms to return list bank
                security: Bearer
                responses:
                    '200':
                        description: Successful list bank according search filter
                        schema:
                            $ref: "#/definitions/ListBankOutput"
            #### Bank Account ####
            /api/bank-accounts:
                post:
                    tags:
                        - Bank account
                    summary: Create bank account
                    description: Create bank account for auth user and return list bank account
                parameters:
                    - in: body
                      name: body
                      required: true
                      schema:
                          $ref: "#/definitions/PayloadNewBankAccountInput"


        definitions:
            PayloadNewBankAccountInput:
                type: object
                properties:
                    cfgBank:
                        type: string
                        required: true
                    name:
                        type: string
                        required: true
                    initialBalance:
                        type: number
                        required: true
            ListBankAccountOutput:
                type: array
                items:
                    $ref: "#/definitions/BankDetailOutput"
            BankDetailOutput:
                type: object
                properties:
                    id:
                        type: string
                        required: true
                    name:
                        type: string
                        required: true
                    initialBalance:
                        type: number
                        required: true
                    balance:
                        type: number
                        required: true
                    displayInGroup:
                        type: boolean
                        required: true
                    createdAt:
                        type: string
                        required: true
                    updatedAt:
                        type: string
                        required: true
                    cfgBank:
                        type: object
                        properties:
                            name:
                                type: string
                                required: true
                            slug:
                                type: string
                                required: true

            DefineNewPasswordInput:
                type: object
                properties:
                    email:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
            ListBankOutput:
                type: array
                items:
                    $ref: "#/definitions/BankOutput"
            BankOutput:
                type: object
                properties:
                    name:
                        type: string
                        required: true
                    slug:
                        type: string
                        required: true
            JWTErrorOutput:
                type: object
                properties:
                    message:
                        type: string
                        required: true

            AuthenticationOutput:
                type: object
                properties:
                    token:
                        type: string
                        required: true
                    user:
                        type: object
                        properties:
                            firstname:
                                type: string
                                required: true
                            lastname:
                                type: string
                                required: true
                            username:
                                type: string
                                required: true
                            email:
                                type: string
                                required: true
                            roles:
                                type: array
                                items:
                                    type: string
                    group:
                        type: object
                        properties:
                            name:
                                type: string
                                required: false
                            slug:
                                type: string
                                required: false
                            owner:
                                type: string
                                required: false
            EmailInput:
                type: object
                properties:
                    email:
                        type: string
                        required: true
            AuthenticationContent:
                type: object
                properties:
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
            RegistrationInput:
                type: object
                properties:
                    firstname:
                        type: string
                        required: true
                    lastname:
                        type: string
                        required: true
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
                    email:
                        type: string
                        required: true
