nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        paths:
            /api/login_check:
                post:
                    tags:
                        - Security
                    sumarry: Authentication
                parameters:
                    -   in: body
                        name: body
                        required: true
                        schema:
                            $ref: "#/definitions/AuthenticationContent"
            /account/registration:
                post:
                    tags:
                        - Account
                    sumarry: Registration
                parameters:
                    -   in: body
                        name: body
                        required: true
                        schema:
                            $ref: "#/definitions/RegistrationInput"
                responses:
                    '201':
                        description: Successful registration
                    '400':
                        description: Bad request. Check your request
        definitions:
            AuthenticationContent:
                type: object
                properties:
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
            RegistrationInput:
                type: object
                properties:
                    firstname:
                        type: string
                        required: true
                    lastname:
                        type: string
                        required: true
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
                    email:
                        type: string
                        required: true
