nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    documentation:
        info:
            title: Budget API
            description: All API related Budget application
            version: 1.0.0
        paths:
            /api/login_check:
                post:
                    tags:
                        - Security
                    sumarry: Authentication
                parameters:
                    -   in: body
                        name: body
                        required: true
                        schema:
                            $ref: "#/definitions/AuthenticationContent"
            /api/accounts:
                post:
                    tags:
                        - Account
                    sumarry: Registration
                    description: Allow user to register to application
                parameters:
                    -   in: body
                        name: body
                        required: true
                        schema:
                            $ref: "#/definitions/RegistrationInput"
                responses:
                    '201':
                        description: Successful registration
                    '400':
                        description: Bad request. Check your request
            /api/accounts/confirm:
                post:
                    tags:
                        - Account
                    summarry: Confirmation account
                    description: Allow user to confirm registration
                parameters:
                    - in: body
                      name: body
                      required: true
                      schema:
                          $ref: "#/definitions/ConfirmAccountInput"
                    - in: query
                      name: tokenActivation
                      type: string
                      required: true
                responses:
                    '200':
                        description: Successful registration confirmation
                        schema:
                            $ref: "#/definitions/AuthenticationOutput"
                    '400':
                        description: Bad request. Check your request.


        definitions:
            AuthenticationOutput:
                type: object
                properties:
                    token:
                        type: string
                        required: true
                    user:
                        type: object
                        properties:
                            firstname:
                                type: string
                                required: true
                            lastname:
                                type: string
                                required: true
                            username:
                                type: string
                                required: true
                            email:
                                type: string
                                required: true
                            roles:
                                type: array
                                items:
                                    type: string
                    group:
                        type: object
                        properties:
                            name:
                                type: string
                                required: false
                            slug:
                                type: string
                                required: false
                            owner:
                                type: string
                                required: false
            ConfirmAccountInput:
                type: object
                properties:
                    email:
                        type: string
                        required: true
            AuthenticationContent:
                type: object
                properties:
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
            RegistrationInput:
                type: object
                properties:
                    firstname:
                        type: string
                        required: true
                    lastname:
                        type: string
                        required: true
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
                    email:
                        type: string
                        required: true
