parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Domain/DoctrineMigrations,Tests,Kernel.php}'

    App\Actions\:
        resource: '../src/Actions'
        tags: ['controller.service_arguments']

    App\Domain\Common\Subscribers\TimestampableSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\Domain\Account\Authentication\Subscribers\AuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
    App\Domain\Account\Authentication\Subscribers\AuthenticationFailureListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }
    App\Domain\Account\Authentication\Subscribers\JWTInvalidListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }
    App\Domain\Account\Authentication\Subscribers\JWTExpiredListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }
